import { z } from "zod";

const envSchema = z.object({
  WORDPRESS_GRAPHQL_URL: z.string().url(),
  WORDPRESS_PREVIEW_SECRET: z.string().min(1),
  WORDPRESS_PREVIEW_AUTH_TOKEN: z.string().min(1),
  NEXT_PUBLIC_SITE_URL: z.string().url(),
  REVALIDATION_SECRET: z.string().min(1),
  HUBSPOT_PORTAL_ID: z.string().min(1),
  HUBSPOT_PRIVATE_APP_TOKEN: z.string().min(1),
  HUBSPOT_FORM_GUID_DEMO: z.string().min(1),
  HUBSPOT_FORM_GUID_WAITLIST: z.string().min(1),
  HUBSPOT_FORM_GUID_CONTACT: z.string().min(1),
});

export const env = envSchema.parse({
  WORDPRESS_GRAPHQL_URL: process.env.WORDPRESS_GRAPHQL_URL,
  WORDPRESS_PREVIEW_SECRET: process.env.WORDPRESS_PREVIEW_SECRET,
  WORDPRESS_PREVIEW_AUTH_TOKEN: process.env.WORDPRESS_PREVIEW_AUTH_TOKEN,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  REVALIDATION_SECRET: process.env.REVALIDATION_SECRET,
  HUBSPOT_PORTAL_ID: process.env.HUBSPOT_PORTAL_ID,
  HUBSPOT_PRIVATE_APP_TOKEN: process.env.HUBSPOT_PRIVATE_APP_TOKEN,
  HUBSPOT_FORM_GUID_DEMO: process.env.HUBSPOT_FORM_GUID_DEMO,
  HUBSPOT_FORM_GUID_WAITLIST: process.env.HUBSPOT_FORM_GUID_WAITLIST,
  HUBSPOT_FORM_GUID_CONTACT: process.env.HUBSPOT_FORM_GUID_CONTACT,
});
